let foundPlaces = [
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Article, Materiel & Salle de Sport',
        'Nom/enseigne': 'ETS BOUANAN MOHAMED',
        Adresse: '68 AVENUE MOHAMMED V',
        Quartier: '',
        Ville: 'AL HOCEIMA',
        postcode: 0,
        latitude: 36.8189381,
        longitude: 10.1824033,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Article, Materiel & Salle de Sport',
        'Nom/enseigne': 'ETS BOUANAN MOHAMED',
        Adresse: '68 AVENUE MOHAMMED V',
        Quartier: '',
        Ville: 'AL HOCEIMA',
        postcode: 0,
        latitude: 36.8189381,
        longitude: 10.1824033,
    },
    {
        TypeS_Fichier: 'MIDA',
        Spécialité: 'Snack/ Café/ Restaurant',
        'Nom/enseigne': 'CAFE SNACK AGZOUZ',
        Adresse: 'SOUIRIA EL KEDIMA',
        Quartier: '',
        Ville: 'SAFI',
        postcode: 0,
        latitude: 32.0369779,
        longitude: -9.336789699999999,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Accessoires & Habillement',
        'Nom/enseigne': 'KEYZA',
        Adresse: 'RUE TANGEROIS VERS BRAHIM ROUDANI 47 RUE ABDELLAH RAJII',
        Quartier: 'EL MAARIF',
        Ville: 'CASABLANCA',
        postcode: '20330',
        latitude: 33.5844922,
        longitude: -7.6360395,
    },
    {
        TypeS_Fichier: 'mida',
        Spécialité: 'DIVERS',
        'Nom/enseigne': 'F-SHOP',
        Adresse: 'fshop.ma',
        Quartier: 'EL LIGNE',
        Ville: 'CASABLANCA',
        postcode: '20250',
        latitude: 33.594268,
        longitude: -7.6087993,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Divers',
        'Nom/enseigne': 'F-SHOP',
        Adresse: 'fshop.ma',
        Quartier: 'EN LIGNE',
        Ville: 'CASABLANCA',
        postcode: '20250',
        latitude: 33.594268,
        longitude: -7.6087993,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Ameublement, Décoration & Accessoires de Maison',
        'Nom/enseigne': 'HOME LINE',
        Adresse: '65 AVENUE 2 MARS',
        Quartier: 'MERS SULTAN',
        Ville: 'CASABLANCA',
        postcode: '20250',
        latitude: 33.5729927,
        longitude: -7.614398199999999,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Eléctromenager',
        'Nom/enseigne': 'ETABLISSEMENT MED LAHLOU',
        Adresse: '70 72 AVENUE HOUMANE EL FETOUAKI',
        Quartier: 'DERB OMAR',
        Ville: 'CASABLANCA',
        postcode: '20001',
        latitude: 33.5933373,
        longitude: -7.6129165,
    },
    {
        TypeS_Fichier: 'MIDA',
        Spécialité: 'Snack/ Café/ Restaurant',
        'Nom/enseigne': 'PLAYA DEL MAR',
        Adresse: 'Plage privé Dar BOUAZA',
        Quartier: 'DAR BOUAZA',
        Ville: 'CASABLANCA',
        postcode: 0,
        latitude: 33.5146259,
        longitude: -7.861143599999999,
    },
    {
        TypeS_Fichier: 'MIDA',
        Spécialité: 'Super & Hypermarché',
        'Nom/enseigne': 'CARREFOUR MARKET',
        Adresse: 'EX FRANPRIX AVENUE MOULAY THAMI 52 BOULEVARD OUED OUM RABIA',
        Quartier: 'HAY OULFA',
        Ville: 'CASABLANCA',
        postcode: '20250',
        latitude: 33.565783,
        longitude: -7.6685789,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Super & Hypermarché',
        'Nom/enseigne': 'CARREFOUR MARKET',
        Adresse: 'EX FRANPRIX AVENUE MOULAY THAMI 52 BOULEVARD OUED OUM RABIA',
        Quartier: 'HAY OULFA',
        Ville: 'CASABLANCA',
        postcode: '20250',
        latitude: 33.565783,
        longitude: -7.6685789,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Accessoires & Habillement',
        'Nom/enseigne': 'TIKI',
        Adresse: 'PARC D ACTIVITE MARJANE KM ROUTE DES FACULTES',
        Quartier: '',
        Ville: 'MOHAMMEDIA',
        postcode: 0,
        latitude: 35.7269008,
        longitude: -5.7567488,
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Ameublement, Décoration & Accessoires de Maison',
        'Nom/enseigne': 'MOBILIA',
        Adresse: 'CENTRE COMMERCIAL ACIMA BOULEVARD HASSAN II',
        Quartier: '',
        Ville: 'TEMARA',
        postcode: '80000',
        latitude: 30.4110744,
        longitude: -9.5615524,
    },
]

let places = [
    {
        TypeS_Fichier: 'MIDA',
        Spécialité: 'Super & Hypermarché',
        'Nom/enseigne': 'CARREFOUR MARKET',
        Adresse: 'EX FRANPRIX AVENUE MOULAY THAMI 52 BOULEVARD OUED OUM RABIA',
        Quartier: 'HAY OULFA',
        Ville: 'CASABLANCA',
    },
    {
        TypeS_Fichier: 'MIDA',
        Spécialité: 'Snack/ Café/ Restaurant',
        'Nom/enseigne': 'CAFE SNACK AGZOUZ',
        Adresse: 'SOUIRIA EL KEDIMA',
        Quartier: '',
        Ville: 'SAFI',
    },
    {
        TypeS_Fichier: 'mida',
        Spécialité: 'DIVERS',
        'Nom/enseigne': 'F-SHOP',
        Adresse: 'fshop.ma',
        Quartier: 'EL LIGNE',
        Ville: 'CASABLANCA',
    },
    {
        TypeS_Fichier: 'MIDA',
        Spécialité: 'Snack/ Café/ Restaurant',
        'Nom/enseigne': 'PLAYA DEL MAR',
        Adresse: 'Plage privé Dar BOUAZA',
        Quartier: 'DAR BOUAZA',
        Ville: 'CASABLANCA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Eléctromenager',
        'Nom/enseigne': 'ETABLISSEMENT MED LAHLOU',
        Adresse: '70 72 AVENUE HOUMANE EL FETOUAKI',
        Quartier: 'DERB OMAR',
        Ville: 'CASABLANCA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Accessoires & Habillement',
        'Nom/enseigne': 'KEYZA',
        Adresse: 'RUE TANGEROIS VERS BRAHIM ROUDANI 47 RUE ABDELLAH RAJII',
        Quartier: 'EL MAARIF',
        Ville: 'CASABLANCA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Ameublement, Décoration & Accessoires de Maison',
        'Nom/enseigne': 'HOME LINE',
        Adresse: '65 AVENUE 2 MARS',
        Quartier: 'MERS SULTAN',
        Ville: 'CASABLANCA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Super & Hypermarché',
        'Nom/enseigne': 'CARREFOUR MARKET',
        Adresse: 'EX FRANPRIX AVENUE MOULAY THAMI 52 BOULEVARD OUED OUM RABIA',
        Quartier: 'HAY OULFA',
        Ville: 'CASABLANCA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Article, Materiel & Salle de Sport',
        'Nom/enseigne': 'ETS BOUANAN MOHAMED',
        Adresse: '68 AVENUE MOHAMMED V',
        Quartier: '',
        Ville: 'AL HOCEIMA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Article, Materiel & Salle de Sport',
        'Nom/enseigne': 'ETS BOUANAN MOHAMED',
        Adresse: '68 AVENUE MOHAMMED V',
        Quartier: '',
        Ville: 'AL HOCEIMA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Accessoires & Habillement',
        'Nom/enseigne': 'TIKI',
        Adresse: 'PARC D ACTIVITE MARJANE KM ROUTE DES FACULTES',
        Quartier: '',
        Ville: 'MOHAMMEDIA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Accessoires & Habillement',
        'Nom/enseigne': 'DIAMANTINE',
        Adresse: 'BOUTIQUE N BR 12 MARJANE',
        Quartier: '',
        Ville: 'SALE',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Café, Restaurant & Patisserie',
        'Nom/enseigne': "MC DONALD'S",
        Adresse: 'CENTRE COMMERCIAL MARJANE ROUTE NATIONALE 1',
        Quartier: 'CHARF SOUANI',
        Ville: 'TANGER',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Ameublement, Décoration & Accessoires de Maison',
        'Nom/enseigne': 'MOBILIA',
        Adresse: 'CENTRE COMMERCIAL ACIMA BOULEVARD HASSAN II',
        Quartier: '',
        Ville: 'TEMARA',
    },
    {
        TypeS_Fichier: 'CADO',
        Spécialité: 'Divers',
        'Nom/enseigne': 'F-SHOP',
        Adresse: 'fshop.ma',
        Quartier: 'EN LIGNE',
        Ville: 'CASABLANCA',
    },
]

let unfoundPlaces = places.filter((el) => {
    return !foundPlaces.some(
        (subEl) =>
            subEl.Type == el.Type &&
            subEl.Specialite == el.Specialite &&
            subEl.Adresse == el.Adresse &&
            subEl.Quartier == el.Quartier &&
            subEl.Ville == el.Ville
    )
})

console.log('unfoundPlaces', unfoundPlaces)
// [
//     ({
//         TypeS_Fichier: 'CADO',
//         Spécialité: 'Accessoires & Habillement',
//         'Nom/enseigne': 'DIAMANTINE',
//         Adresse: 'BOUTIQUE N BR 12 MARJANE',
//         Quartier: '',
//         Ville: 'SALE',
//     },
//     {
//         TypeS_Fichier: 'CADO',
//         Spécialité: 'Café, Restaurant & Patisserie',
//         'Nom/enseigne': "MC DONALD'S",
//         Adresse: 'CENTRE COMMERCIAL MARJANE ROUTE NATIONALE 1',
//         Quartier: 'CHARF SOUANI',
//         Ville: 'TANGER',
//     })
// ]
